# Generated by Django 2.2.4 on 2025-07-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200510_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
