# Generated by Django 2.2.4 on 2025-07-31 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250730_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='apartment_address',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='zip',
        ),
    ]
